//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.Venta_Detalle = new HashSet<Venta_Detalle>();
        }
    
        public int VentaID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaRenta { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> FechaRealDevolucion { get; set; }
        public Nullable<decimal> Multa { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Venta_Detalle> Venta_Detalle { get; set; }
    }
}
